"""add user model



Revision ID: 90865e1a389e
Revises: 88b9d1e9b32b
Create Date: 2023-10-19 01:57:49.378728

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '90865e1a389e'
down_revision = '88b9d1e9b32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False, comment='user name'),
                    sa.Column('password', sa.String(length=256), nullable=False, comment='user password'),
                    sa.Column('e_mail', sa.String(length=256), nullable=False, comment='user e_mail'),
                    sa.Column('is_enabled', sa.Boolean(), nullable=True, comment='is enabled'),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
                    sa.UniqueConstraint('e_mail', name=op.f('uq_users_e_mail')),
                    sa.UniqueConstraint('name', name=op.f('uq_users_name')),
                    schema='public'
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='public')
    # ### end Alembic commands ###
