version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached
    env_file: app.env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  db:
    container_name: postgres
    image: postgres:14.4-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: app.env
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  web:
    container_name: web
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/ssl:/etc/nginx/ssl
  schemaspy:
    image: schemaspy/schemaspy:snapshot
    container_name: "schemaspy"
    volumes:
      - ./schemaspy/output:/output
      - ./schemaspy/postgresql-42.4.0.jar:/postgresql-42.4.0.jar
      - ./schemaspy/make.sh:/make.sh
    tty: true
    entrypoint: /bin/sh
    env_file: app.env
  schemaspy_web:
    image: nginx:alpine
    container_name: "schemaspy_web"
    ports:
      - "8081:80"
    volumes:
      - ./schemaspy/output:/usr/share/nginx/html
volumes:
  postgres-data:
